# Generated by Django 5.1.7 on 2025-03-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField(blank=True, null=True, verbose_name='Номер стола')),
                ('items', models.CharField(blank=True, null=True, verbose_name='Список заказанных блюд с ценами')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Общая стоимость заказа')),
                ('status', models.CharField(blank=True, choices=[('pending', 'В ожидании'), ('ready', 'Готово'), ('paid', 'Оплачено')], default='pending', null=True, verbose_name='Статус заказа')),
            ],
            options={
                'verbose_name': 'Кафе',
                'verbose_name_plural': 'Кафе',
                'ordering': ('table_number',),
            },
        ),
    ]
