# Generated by Django 5.1.7 on 2025-03-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='table_number',
            field=models.IntegerField(blank=True, choices=[(1, 'Стол 1'), (2, 'Стол 2'), (3, 'Стол 3'), (4, 'Стол 4'), (5, 'Стол 5')], null=True, verbose_name='Номер стола'),
        ),
    ]
