# Generated by Django 5.1.7 on 2025-03-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_alter_cafe_table_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
                'ordering': ('name', 'price'),
            },
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='items',
        ),
        migrations.AddField(
            model_name='cafe',
            name='items',
            field=models.ManyToManyField(to='back.menuitem'),
        ),
    ]
