# Generated by Django 5.1.7 on 2025-03-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_menuitem_remove_cafe_items_cafe_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='items',
            field=models.ManyToManyField(to='back.menuitem', verbose_name='Меню'),
        ),
    ]
